version: "3"

services:
  wg-easy:
    environment:
      # IP pública o Hostname:
      - WG_HOST=xxxxxxxxxx.duckdns.org
      # Idioma es=Español:
      - LANG=es
      # Contraseña interfaz web UI: #Cambiar un $ por $$. Comando generar hash; docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw
      - PASSWORD_HASH= #https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
      # Dirección IP del contenedor Pihole
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy-hole
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  pihole:
    image: pihole/pihole
    container_name: pihole-hole
    environment:
      # Contraseña interfaz web Pihole UI:
      - WEBPASSWORD=p4ssw0rd
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
